IF
	OnCreation()
	Global("pxl2ranc","LOCALS",0)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@30219)
		Wait(2)
		SetGlobal("pxl2ranc","LOCALS",1)
END

IF
	Global("pxl2ranc","LOCALS",1)
	See(NearestEnemyOf(Myself))
	OR(3)
		General(NearestEnemyOf(Myself),UNDEAD)
		General(NearestEnemyOf(Myself),GIANTHUMANOID)
		General(NearestEnemyOf(Myself),MONSTER)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@30229)
		SetGlobal("pxl2ranc","LOCALS",2)
END